server:
  port: 80

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8


  datasource:
    url: jdbc:mysql://127.0.0.1/prize?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
#    url: jdbc:mysql://10.9.29.223:3306/prize?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: llp
#    password: Redr0ck;D0nt;Fuck;Me;

  redis:
    host: localhost
    port: 6379
    database: 12
    password:
    timeout: 500ms

    jedis:
      pool:
        max-idle: 8
        min-idle: 2
        max-active: 8
        max-wait: 10000ms
mybatis:
  type-aliases-package: team.redrock.prize.bean


prjPath: accept_prize/

WX_APPID: "wx81a4a4b77ec98ff4"
WX_APPSECRET: "58e74928490b55bebb483fc526828bfc"
REDIRECT_URI: " http://65v7bh.natappfree.cc"

OPENIDTemp: "o08-k1CAlytHhsEFrnfnaA-W4FDo"
TEMPLATE_ID: "1RvFGl6KG5owcjPNuNZ9iJsVonuMWqHZpGmlsgFi2eY"
SENDURL: "https://api.weixin.qq.com/cgi-bin/message/template/send?access_token="
AccessTokenApi: "https://wx.idsbllp.cn/game/api/accesstoken.php"
#AccessTokenApi: "https://yangruixin.com/transmit.php"
#GetOpenidUrl: "https://wx.idsbllp.cn/MagicLoop/index.php?s=/addon/Api/Api/getOpenidByStuId"
GetOpenidUrl: "http://hongyan.cqupt.edu.cn/MagicLoop/index.php?s=/addon/Api/Api/getOpenidByStuId"
GetuserinfoUrl: "http://hongyan.cqupt.edu.cn/MagicLoop/index.php?s=/addon/Api/Api/bindVerify"
#GetuserinfoUrl: "https://wx.idsbllp.cn/MagicLoop/index.php?s=/addon/Api/Api/bindVerify"
PosterUtil.timestamp: "1505118409"
PosterUtil.string: "asdfghjkl"
PosterUtil.secret: "e49e89f65d0319bdce2d4740c5b2244af2e774e8"